### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by alaarman** [sebastiaanbrand/q-sylvan#1]
I get the following error. It seems a library is needed, but unbeknown to cmake. This is on macos.

/Users/laarman/Projects/q-sylvan/src/edge_weight_storage/flt.h:10:10: fatal error: 'quadmath.h' file not found
#include <quadmath.h>
         ^~~~~~~~~~~~

**Comment by sebastiaanbrand** [comment]
This might be because the 128 bit floating points have different headers/implementations on MacOS vs Linux. The latest commit might fix this.

**Comment by alaarman** [comment]
Works
